# config.py

SEARCH_KEYWORDS = [
    # Real Estate Keywords
    "Realtor contact email",
    "Real Estate Agent contact info",
    "Real Estate Broker email address",
    "Real Estate Investor contact",
    "Property Manager email",
    "Real Estate Developer email",
    "Mortgage Broker email contact",
    "Loan Officer contact info",
    "Mortgage Insurance Agent email",
    "Title Agent email address",
    "Real Estate Attorney contact",
    "Appraiser email",
    "Home Inspector contact email",
    "Escrow Officer email",
    "Commercial Real Estate Agent contact",
    "Luxury Real Estate Agent email",
    "Real Estate Photographer email",
    "Airbnb Manager contact email",
    "Real Estate Coach email address",
    "Real Estate Mentor contact",
    "Real Estate Syndicator email",
    "Real Estate Influencer contact email",

    # Mixed Niches Keywords
    "Startup Founder contact email",
    "Entrepreneur email contact",
    "Business Coach email",
    "Podcast Host contact",
    "YouTuber business email",
    "Content Creator email",
    "Influencer business contact",
    "Health Coach email",
    "Fitness Trainer contact",
    "Nutritionist email contact",
    "Life Coach email",
    "Public Speaker contact email",
    "Author contact",
    "Course Creator email",
    "Digital Marketer email contact",
    "Marketing Consultant contact",
    "Personal Brand Strategist email",
    "E-commerce Business Owner contact",
    "Shopify Owner email",
    "Angel Investor contact email",
    "Venture Capitalist email",

    # Banking and Finance Keywords
    "Private Banker contact email",
    "Wealth Manager email",
    "Financial Advisor contact",
    "Investment Banker email address",
    "Loan Officer email contact",
    "Credit Analyst contact",
    "Mortgage Broker email",
    "Bank Branch Manager email",
    "Commercial Banker contact",
    "Retail Banker email",
    "Fintech Founder contact",
    "Hedge Fund Manager email",
    "Risk Management Consultant email",
    "Insurance Agent email address",
    "Treasury Analyst contact email",
    "Corporate Finance Consultant email",
    "Estate Planner contact email",
    "Tax Consultant email",
    "Financial Planner contact"
]

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}
